# Generated by Django 5.1.1 on 2024-10-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_producto_precio_alter_producto_costo'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='producto',
            order_with_respect_to='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
    ]
